// UI-owned text only. Provider content, user labels, commands and errors retain their source language.
var chinese = {
"Check and update Perch":"检查并更新 Perch",
"Automatically update Perch":"自动更新 Perch",
"Every six hours through Omarchy; clean default-branch installs only":"每六小时通过 Omarchy 更新；仅限无本地改动的默认分支安装",
"Codex approvals":"Codex 授权请求",
"Explicit Allow once or Deny; review and trust in Codex /hooks":"明确选择允许一次或拒绝；请在 Codex /hooks 中审核并信任",
"Open workspace":"打开工作区",
"Discover recent local sessions":"发现最近的本地会话",
"Read bounded session metadata; show last seen without live alerts":"仅读取有限的会话元数据；显示最近记录，不触发实时提醒",
"Working, approval attention and completion; review and trust in Codex /hooks":"工作、授权提醒和完成状态；请在 Codex /hooks 中审核并信任",
"Working and completion; local extension":"通过本地扩展显示工作和完成状态",
"Working, permission attention and completion; local extension":"通过本地扩展显示工作、授权提醒和完成状态",
"Placement":"位置", "Behaviour":"行为", "Alerts & sound":"提醒与声音", "Your strip":"工具栏", "Plugin pins":"固定插件",
"Choose where Perch lives on your desktop.":"选择 Perch 在桌面上的位置。", "Control how Perch opens and moves.":"控制 Perch 的展开方式和动画。",
"Choose interruptions, previews and sounds.":"选择提醒、预览和声音。", "Choose and arrange up to eight tools and plugin pins.":"选择并排列最多八个工具或插件。",
"Pin plugins for native cards and quick access to their full panels.":"固定插件，使用原生卡片并快速打开完整面板。",
"Changes apply automatically":"更改自动生效", "Compact presentation":"紧凑视图", "Notch":"灵动岛", "Module strip":"工具栏",
"Dark island":"深色灵动岛", "Follow Omarchy theme":"跟随 Omarchy 主题", "Follow focused display":"跟随当前显示器",
"Hide Perch":"隐藏 Perch", "Show timer and activity alerts":"显示计时器和活动提醒", "Keep Perch visible":"始终显示 Perch",
"Quiet mode":"安静模式", "Pause automatic cards, previews, sounds and timer notifications. Timers and the inbox keep working.":"暂停自动卡片、预览、声音和计时通知。计时器与收件箱继续运行。",
"Notification previews":"通知预览", "Briefly show new notifications ahead of music and running timers.":"短暂优先显示新通知，然后恢复音乐或计时器。",
"Activity sounds":"活动声音", "Play a sound for new completion or attention events.":"活动完成或需要处理时播放声音。",
"Device feedback":"设备反馈", "Show volume, power and Bluetooth changes.":"显示音量、电源和蓝牙状态变化。",
"Timer sound":"计时器声音", "Play a sound when a timer finishes.":"计时结束时播放声音。",
"Timer notifications":"计时器通知", "Send completed timers to desktop notifications.":"计时结束时发送桌面通知。",
"Remote cover artwork":"在线封面", "Allow downloading cover images from your media player.":"允许下载媒体播放器提供的封面。",
"Activity cards":"活动卡片", "Open new completion and attention cards while Perch is collapsed.":"Perch 收起时显示新的完成或待处理卡片。",
"Remember agent sessions":"记住智能体会话", "Keep up to eight last-seen sessions for one day across shell restarts. Pending requests are never saved.":"重启桌面后保留最多八个最近会话，有效期一天。不保存待处理请求。",
"Alert sound":"提醒声音", "Complete":"已完成", "Message":"消息", "Bell":"铃声", "Preview sound":"试听",
"Inbox Do Not Disturb also silences Perch sounds. Sound playback needs canberra-gtk-play.":"收件箱的勿扰模式也会静音 Perch。播放声音需要 canberra-gtk-play。",
"Strip modules · up to eight":"工具栏模块 · 最多八个", "Pin installed plugins":"固定已安装的插件", "Refresh":"刷新", "Pin":"固定", "Unpin":"取消固定",
"Shortcuts work while Perch has keyboard focus. Use Ctrl+Alt and a letter or digit. Escape cancels recording.":"快捷键在 Perch 获得键盘焦点时生效。使用 Ctrl+Alt 加字母或数字。按 Esc 取消录制。",
"That shortcut is already assigned.":"该快捷键已被使用。", "Clear":"清除", "Record":"录制", "Press Ctrl+Alt+key…":"请按 Ctrl+Alt+按键…",
"Drag tiles to reorder, or focus one and use Ctrl + arrow keys. Cards keep the strip visible for switching.":"拖动图块排序，或选中后按 Ctrl 加方向键。卡片展开时工具栏保持可见。",
"Plugin discovery unavailable":"无法发现插件", "Checking installed plugins…":"正在检查已安装的插件…",
"No installed plugins with a supported panel. Install and enable plugins through Omarchy.":"没有支持面板的已安装插件。请通过 Omarchy 安装并启用插件。",
"Click a pinned plugin to open its own panel. Disabled plugins must first be enabled in Omarchy.":"点击固定插件可打开其面板。已禁用的插件需要先在 Omarchy 中启用。",
"Music":"音乐", "Timers":"计时器", "Timer":"计时器", "Clipboard":"剪贴板", "System stats":"系统状态", "Weather":"天气", "Files":"文件", "Calendar":"日历", "Activity":"活动", "Devices":"设备", "Inbox":"收件箱", "Apps":"应用", "AI usage":"AI 用量", "Usage":"用量", "Stats":"状态",
"All tools and plugins":"所有工具和插件", "Setup & health":"设置与检查", "Open":"打开", "Done":"完成", "Configure":"配置", "Module unavailable":"模块不可用",
"Plugin drawer":"插件抽屉", "Something needs attention":"有事项需要处理", "Permission needed":"需要授权", "Input needed":"需要输入", "Needs your attention":"需要你处理",
"Perch settings":"Perch 设置", "Notifications":"通知", "Back to card":"返回卡片", "Settings":"设置", "Collapse Perch":"收起 Perch",
"Working…":"正在处理…", "Playing":"播放中", "Paused":"已暂停", "Previous track":"上一曲", "Pause":"暂停", "Play":"播放", "Next track":"下一曲", "Switch player":"切换播放器", "Load lyrics":"加载歌词", "Read lyrics":"阅读歌词",
"Play music or a video.\nYour controls will appear here.":"播放音乐或视频后，\n控制按钮会显示在这里。",
"Make Perch yours":"按你的喜好设置 Perch", "Check":"检查", "Choose what Perch handles. Notifications and system feedback replace their built-in counterparts; disabling restores them.":"选择由 Perch 处理的功能。通知和设备反馈会替换内置功能；禁用后恢复原状。",
"Claude approvals & questions":"Claude 授权与问答", "Explicit responses in Perch; tool inputs visible only while a request is pending":"在 Perch 中明确回复；仅在请求待处理期间显示工具输入",
"Claude usage status line":"Claude 用量状态栏", "Opt-in local rate-limit counters; preserves custom status lines":"可选的本地用量计数；保留自定义状态栏",
"Inbox, replies and persistent history":"收件箱、回复和持久历史", "System feedback":"设备反馈", "One set of volume and brightness overlays":"统一的音量和亮度浮层",
"Working, attention and completion":"工作状态、待处理提醒和完成", "Working, permission attention and completion; respond in Gemini":"工作状态、授权提醒和完成；请在 Gemini 中回复",
"Working, completion and errors; local desktop sessions":"本地桌面会话的工作状态、完成和错误", "Turn completion only":"仅报告回合完成", "Update now":"立即更新", "Update":"更新", "Disable":"禁用", "Enable":"启用",
"Confirm: restore defaults and remove hooks":"确认：恢复默认功能并移除钩子", "Prepare Perch for removal":"准备移除 Perch",
"Run this before disabling or removing Perch. Saved files, calendars and history are retained; shelf originals are never deleted.":"禁用或移除 Perch 前运行此操作。保留已保存的文件、日历和历史；不会删除文件架中的原文件。",
"Quick access to Omarchy":"快速访问 Omarchy", "No installed apps loaded":"未加载已安装的应用", "Application to launch or pin":"要启动或固定的应用", "Pinned links":"固定链接", "Name":"名称", "Pin link":"固定链接",
"Loading request…":"正在加载请求…", "Select options or type your answer":"选择选项或输入答案", "Choose or type your answer":"选择或输入答案", "Send answers":"发送答案", "Allow once":"仅允许一次", "Deny":"拒绝", "Answer in session":"在会话中回复",
"Expired. Continue in your agent session.":"请求已过期。请在智能体会话中继续。", "Request is unavailable.":"请求不可用。", "Review request":"查看请求", "Go to session":"返回会话", "Opening…":"正在打开…", "Needs attention":"待处理", "Failed":"失败", "Last seen":"最近出现", "In progress":"进行中",
"This activity has finished":"此活动已结束", "Review this request in your agent session.":"请在智能体会话中查看此请求。", "Continue in your session when you’re ready.":"准备好后请在会话中继续。",
"Disable usage":"停用用量读取", "Enable local usage":"启用本地用量", "Reading counters…":"正在读取计数…", "Snapshots are not live billing data. Refresh after another agent response.":"快照不是实时账单数据。智能体再次回复后可刷新。",
"Read usage counters from local Codex sessions and the optional Claude status-line bridge. No account login or credential access.":"从本地 Codex 会话和可选的 Claude 状态栏桥接读取用量计数。无需登录，也不会读取凭据。",
"Enable Claude usage in Setup, then start a terminal session. Your client and account must expose rate limits.":"在设置中启用 Claude 用量，然后启动终端会话。客户端和账户需提供用量限制数据。",
"Run Codex locally to populate a usage snapshot.":"在本地运行 Codex 以生成用量快照。",
"Search tools and plugins":"搜索工具和插件", "No matching tools or plugins":"没有匹配的工具或插件", "Search clipboard":"搜索剪贴板", "Copy":"复制", "Copied":"已复制", "No clipboard items":"剪贴板为空",
"Start":"开始", "Resume":"继续", "Cancel":"取消", "Repeat":"重复", "Snooze":"稍后提醒", "Add timer":"添加计时器", "Label":"名称", "Minutes":"分钟", "Join":"加入会议", "Add calendar":"添加日历", "Remove":"移除", "Mute":"静音", "Unmute":"取消静音", "Do Not Disturb":"勿扰模式", "Clear history":"清空历史", "Mark all read":"全部标为已读", "All applications":"所有应用",
"Language":"语言", "Interface language":"界面语言", "English":"English"
};
Object.assign(chinese,{
  "Plugin Perch": "插件工具栏",
  "Keep your chosen tools and plugin pins visible at the edge.": "在屏幕边缘持续显示所选工具和固定插件。",
  "Show one useful context. Your tools and pins appear when you open Perch.": "显示当前最有用的信息。展开 Perch 后显示工具和固定插件。",
  "Appearance": "外观",
  "Display": "显示器",
  "Per-display placement": "按显示器保存位置",
  "Remember a different edge and size for each display.": "为每个显示器记住不同的位置和尺寸。",
  "Screen edge": "屏幕边缘",
  "Card width": "卡片宽度",
  "Extra edge spacing": "边缘间距",
  "Attach to screen edge": "贴合屏幕边缘",
  "Remove the gap between Perch and the edge.": "移除 Perch 与屏幕边缘之间的空隙。",
  "Reduce motion": "减少动画",
  "Show cards immediately without transitions.": "立即显示卡片，不播放过渡动画。",
  "Open on hover": "悬停展开",
  "Preview built-in cards by hovering. Plugin pins still need a click.": "悬停预览内置卡片。固定插件仍需点击。",
  "During fullscreen": "全屏时",
  "Integration setup…": "集成设置…",
  "Demo · fictional data": "演示 · 虚构数据",
  "Saved automatically in Omarchy settings": "已自动保存到 Omarchy 设置",
  "Find a tool or plugin…": "查找工具或插件…",
  " result": " 个结果",
  " results": " 个结果",
  "Loading…": "正在加载…",
  "Refresh plugins": "刷新插件",
  "No tools or plugins match. Try another name.": "没有匹配的工具或插件。请尝试其他名称。",
  "Plugin": "插件",
  "Plugin · disabled": "插件 · 已禁用",
  "Built-in tool": "内置工具",
  "Back": "返回",
  "New timer": "新建计时器",
  "Make time for one thing": "专注做好一件事",
  "Time’s up": "时间到",
  "Snooze 5m": "5 分钟后提醒",
  "Name your timer": "计时器名称",
  " min": " 分钟",
  "Timer service is loading": "计时服务正在加载",
  "Up to eight timers. Timers continue while Perch is closed. Completion options are in Settings.": "最多八个计时器。Perch 收起后仍继续计时。结束提醒可在设置中调整。",
  "Your next 30 days": "未来 30 天",
  "Add ICS": "添加 ICS",
  "Choose a calendar export or an ICS file maintained by your sync tool.": "选择日历导出文件，或由同步工具维护的 ICS 文件。",
  "Open meeting link": "打开会议链接",
  "Remove source · ": "移除来源 · ",
  "Search recent clipboard previews…": "搜索最近的剪贴板预览…",
  "Clipboard unavailable": "剪贴板不可用",
  "Reading…": "正在读取…",
  "Select to copy; then paste in your app. History is owned by Omarchy.": "选择后复制，然后在应用中粘贴。历史由 Omarchy 管理。",
  "No matching entries. History is owned by Omarchy.": "没有匹配记录。历史由 Omarchy 管理。",
  "Add files": "添加文件",
  "Drop files here. Drag a card out to another app. Originals stay where they are.": "将文件拖到这里，也可将卡片拖到其他应用。原文件位置不变。",
  " · missing": " · 已丢失",
  "Your shelf is empty": "文件架为空",
  "Use Open to preview this file in its application.": "使用“打开”在对应应用中预览此文件。",
  "DND on": "勿扰已开启",
  "DND off": "勿扰已关闭",
  "Clear all": "清空全部",
  "Enable the optional notification companion to bring previews and history into Perch. See the setup guide.": "启用可选的通知组件，将预览和历史带入 Perch。请参阅设置指南。",
  "You're all caught up": "没有未读通知",
  "Unmute app": "取消应用静音",
  "Mute app": "静音此应用",
  "Read": "已读",
  "Notification": "通知",
  "Dismiss": "关闭",
  "Reply to this notification": "回复此通知",
  "Send": "发送",
  "Sound output": "声音输出",
  "Microphone": "麦克风",
  "Unmute mic": "取消麦克风静音",
  "Mute mic": "麦克风静音",
  "Brightness": "亮度",
  "Unavailable": "不可用",
  "Battery · ": "电池 · ",
  "Charging": "充电中",
  "On battery": "使用电池",
  "Plugged in": "已接通电源",
  "No battery": "无电池",
  "Bluetooth": "蓝牙",
  "Disconnect": "断开",
  "Connect": "连接",
  "No paired Bluetooth devices": "没有已配对的蓝牙设备",
  "Returns to the session in ": "返回会话倒计时：",
  "s. Allow applies to this request only.": " 秒。授权仅适用于本次请求。",
  "1 needs your attention": "1 项需要处理",
  " need your attention": " 项需要处理",
  "now": "刚刚",
  "Builds, downloads, backups.\nLet your scripts report their progress here.": "构建、下载、备份。\n让脚本在这里报告进度。",
  "Connect a script using Perch’s activity command. See the README for examples.": "使用 Perch 的 activity 命令连接脚本。示例见 README。",
  "Browse activities": "浏览活动",
  "Updated ": "更新时间：",
  "% used": "% 已用",
  " · resets ": " · 重置时间：",
  "Usage unavailable in this preview.": "此预览中用量不可用。",
  "Unpin · ": "取消固定 · ",
  "Remove link": "移除链接",
  "Plugin unavailable": "插件不可用",
  "Plugin disabled": "插件已禁用"
});
Object.assign(chinese,{
  "Clear sky": "晴",
  "Cloudy": "多云",
  "Fog": "雾",
  "Rain or drizzle": "雨或毛毛雨",
  "Snow": "雪",
  "Rain showers": "阵雨",
  "Snow showers": "阵雪",
  "Thunderstorms": "雷雨",
  "Selected location": "所选地点",
  "Choose Configure to enable weather for a location.": "选择“配置”，为一个地点启用天气。",
  "Wind ": "风速 ",
  "Weather unavailable": "天气不可用",
  " Showing previous data.": " 正在显示之前的数据。",
  "Updating…": "正在更新…",
  "Weather: Open-Meteo · CC BY 4.0": "天气：Open-Meteo · CC BY 4.0",
  "Location label": "地点名称",
  "Latitude": "纬度",
  "Longitude": "经度",
  "Enabling sends these coordinates to api.open-meteo.com. No automatic location lookup. Updates every 15 minutes while visible.": "启用后会将坐标发送到 api.open-meteo.com。不会自动定位。显示期间每 15 分钟更新。",
  "Save & enable": "保存并启用",
  "Memory": "内存",
  "Root disk": "根磁盘",
  "Measuring…": "正在测量…",
  "Statistics unavailable": "系统状态不可用",
  "Refreshes every ": "刷新间隔：",
  " seconds while visible. CPU history covers the last 30 samples.": " 秒，仅在可见时更新。CPU 历史显示最近 30 次采样。",
  "Refresh interval": "刷新间隔",
  " seconds": " 秒",
  "Sampling stops when neither the stats tile nor its card is visible.": "状态图块和卡片都不可见时停止采样。",
  "Plugin cards are unavailable": "插件卡片不可用",
  "Open the plugin’s full panel, or retry its native card.": "打开插件完整面板，或重试原生卡片。"
});
Object.assign(chinese,{"Receive remote agent status":"接收远程智能体状态","Optional SSH socket forwarding. Status only; permissions stay in the remote session.":"可选的 SSH 套接字转发。仅接收状态；授权仍在远程会话中进行。","Starting receiver…":"正在启动接收器…"});
Object.assign(chinese,{"Working, permission and question attention; local extension":"工作状态、授权和问题提醒；本地扩展","Allow once or deny through the v1 client; questions stay in the session":"通过 v1 客户端允许一次或拒绝；问题仍在会话中回答"});
Object.assign(chinese,{"Open in Codex desktop":"在 Codex 桌面应用中打开"});
Object.assign(chinese,{"Select Zellij pane":"选择 Zellij 窗格"});
Object.assign(chinese,{"Codex server status":"Codex 服务器状态","Read an existing private local control socket every five seconds. Permissions stay in Codex. Uses the bundled Rust WebSocket client.":"每五秒读取现有的私有本地控制套接字。授权仍在 Codex 中处理。使用随附的 Rust WebSocket 客户端。","Absolute control socket path":"控制套接字的绝对路径","Stop reading Codex status":"停止读取 Codex 状态","Read Codex status":"读取 Codex 状态","Checking Codex status…":"正在检查 Codex 状态…"," loaded sessions":" 个已加载会话"});
function translate(text, language) {
    return language === "zh-CN" && Object.prototype.hasOwnProperty.call(chinese,text) ? chinese[text] : text;
}
if (typeof module !== "undefined") module.exports = {translate,chinese};
