const assert = require('node:assert/strict');
const A = require('../ActivityPolicy.js'), P = require('../PreferencesPolicy.js');
const now=1000000;
assert.equal(A.normalize('{bad',now),null);
assert.equal(A.normalize('x'.repeat(4097),now),null);
for (const id of ['', '../bad', '__proto__', 'x'.repeat(65)]) assert.equal(A.normalize(JSON.stringify({id,state:'running'}),now),null);
for (const invalid of [{state:'approve'}, {ttl:0}, {ttl:86401}, {progress:2}, {progress:'NaN'}]) assert.equal(A.normalize(JSON.stringify({id:'job',state:'running',...invalid}),now),null);
const valid=A.normalize(JSON.stringify({id:'build',state:'running',title:'x'.repeat(200),detail:'y'.repeat(400),progress:.5}),now);
assert.equal(valid.title.length,120);assert.equal(valid.detail.length,240);assert.equal(valid.progress,.5);
let items=[];
for(let i=0;i<8;i++) items=A.upsert(items,{...valid,id:'job'+i},now);
assert.equal(A.upsert(items,{...valid,id:'overflow'},now),null);
items=A.upsert(items,{...valid,id:'job0',state:'waiting',updatedAt:now+1},now);
assert.equal(items.length,8);assert.equal(A.focus(items).id,'job0');
assert.equal(A.upsert(items,{...valid,id:'new'},now+300001).length,1);
assert.equal(A.timer({status:'running',deadline:now-1,total:60,remaining:60,label:'Focus'},now).status,'done');
assert.equal(A.timer({status:'running',deadline:Infinity,total:60,remaining:60},now).status,'idle');
assert.equal(P.clean({edge:'bad',showClock:false,hideIdle:'true'}).edge,'top');
assert.equal(P.clean({hideIdle:'true'}).hideIdle,false);
assert.equal(P.clean({showClock:false}).showClock,false);
assert.equal(P.entry('{broken'),null);
assert.equal(P.entry(JSON.stringify({plugins:[{id:'other',secret:'no'},{id:'io.github.tcballard.perch',edge:'right'}]})).edge,'right');
assert.deepEqual(P.entry('{"plugins":[]}'),{});
console.log('Activity limits, expiry/priority, timer restoration and scoped preference parsing passed.');
