const assert = require('node:assert/strict');
const A = require('../ActivityPolicy.js'), P = require('../PreferencesPolicy.js');
const now=1000000;
assert.equal(A.normalize('{bad',now),null);
assert.equal(A.normalize('x'.repeat(4097),now),null);
for (const id of ['', '../bad', '__proto__', 'x'.repeat(65)]) assert.equal(A.normalize(JSON.stringify({id,state:'running'}),now),null);
for (const invalid of [{state:'approve'}, {ttl:0}, {ttl:86401}, {progress:2}, {progress:'NaN'}]) assert.equal(A.normalize(JSON.stringify({id:'job',state:'running',...invalid}),now),null);
const valid=A.normalize(JSON.stringify({id:'build',state:'running',title:'x'.repeat(200),detail:'y'.repeat(400),progress:.5}),now);
assert.equal(valid.title.length,120);assert.equal(valid.detail.length,240);assert.equal(valid.progress,.5);
const agent=A.normalize(JSON.stringify({id:'claude.1',state:'waiting',title:'Perch',kind:'agent',agent:'Claude',project:'perch',target:'0x123abc'}),now);
assert.equal(agent.kind,'agent');assert.equal(agent.project,'perch');assert.equal(agent.target,'0x123abc');
assert.equal(A.normalize(JSON.stringify({id:'bad-target',state:'waiting',kind:'agent',target:'address:$(bad)'}),now).target,'');
let items=[];
for(let i=0;i<32;i++) items=A.upsert(items,{...valid,id:'job'+i},now);
assert.equal(A.upsert(items,{...valid,id:'overflow'},now),null);
items=A.upsert(items,{...valid,id:'job0',state:'waiting',updatedAt:now+1},now);
assert.equal(items.length,32);assert.equal(A.focus(items).id,'job0');
assert.equal(A.attention(items).length,1);
assert.equal(A.upsert(items,{...valid,id:'new'},now+300001).length,1);
const approval={...agent,id:'request.new',requestId:'b'.repeat(32)};
const admitted=A.upsert(items,approval,now);
assert.equal(admitted.length,32);
assert(admitted.some(p=>p.id===approval.id));
assert(admitted.some(p=>p.id==='job0')); // Existing attention survives.
const fullAttention=Array.from({length:32},(_,i)=>({...approval,id:'request.'+i}));
assert.equal(A.upsert(fullAttention,{...approval,id:'overflow'},now),null);
assert.equal(A.upsert(fullAttention,{...approval,id:'request.0'},now).length,32);
const withHistory=items.map((p,i)=>({...p,state:p.id==='job1'?'idle':p.id==='job2'?'done':p.state}));
const refreshed=A.upsert(withHistory,{...valid,id:'fresh'},now);
assert.equal(refreshed.length,32);assert(!refreshed.some(p=>p.id==='job1'));
assert(refreshed.some(p=>p.id==='job2'));
const eightIdle=Array.from({length:8},(_,i)=>({...valid,id:'old.'+i,state:'idle'}));
assert.equal(A.upsert(eightIdle,approval,now).length,9);
assert.equal(A.timer({status:'running',deadline:now-1,total:60,remaining:60,label:'Focus'},now).status,'done');
assert.equal(A.timer({status:'running',deadline:Infinity,total:60,remaining:60},now).status,'idle');
assert.equal(P.clean({edge:'bad',showClock:false,hideIdle:'true'}).edge,'top');
assert.equal(P.clean({hideIdle:'true'}).hideIdle,false);
assert.equal(P.clean({showClock:false}).showClock,false);
assert.equal(P.entry('{broken'),null);
assert.equal(P.entry(JSON.stringify({plugins:[{id:'other',secret:'no'},{id:'io.github.tcballard.perch',edge:'right'}]})).edge,'right');
assert.deepEqual(P.entry('{"plugins":[]}'),{});
console.log('Activity limits, expiry/priority, timer restoration and scoped preference parsing passed.');
const remembered={...agent,updatedAt:now,targetPid:123,targetStart:"100",targetBoot:'12345678-1234-1234-1234-123456789abc',requestId:'a'.repeat(32)};
const snapshot=A.snapshot([remembered,valid]);
assert.equal(snapshot.length,1); assert.equal(snapshot[0].requestId,undefined);
const recovered=A.recover(snapshot,now+1000);
assert.equal(recovered.length,1);assert.equal(recovered[0].state,'idle');
assert.equal(recovered[0].requestId,'');assert.equal(A.focus(recovered),null);
assert.equal(A.recover(snapshot,now+86400001).length,0);
assert.equal(A.recover([{...snapshot[0],updatedAt:now+10000}],now).length,0);
assert.equal(A.recover([{...snapshot[0],targetPid:0}],now)[0].target,'');
assert.equal(P.clean({rememberSessions:true}).rememberSessions,true);
assert.equal(P.clean({}).rememberSessions,false);
console.log('Session recovery strips requests, expires last-seen records and requires target identity.');
const found=A.discovered([],snapshot,now+1000,[]);
assert.equal(found[0].state,'idle');assert.equal(A.focus(found),null);
assert.equal(A.discovered([],snapshot,now+1000,[snapshot[0].id]).length,0);
assert.equal(A.discovered([remembered],snapshot,now+1000,[])[0].state,remembered.state);
assert.equal(P.clean({discoverSessions:true}).discoverSessions,true);
assert.equal(P.clean({}).discoverSessions,false);
console.log('Discovered sessions remain idle, respect dismissal and never overwrite live activity.');
const liveProcess={...agent,state:'running',agentProcess:{pid:123,start:'100',boot:'boot'}};
const check={ended:[agent.id],checked:[{id:agent.id,pid:123,start:'100',boot:'boot'}]};
assert.equal(A.endedProcesses([liveProcess],check,now)[0].state,'idle');
assert.equal(A.endedProcesses([{...liveProcess,agentProcess:{pid:124,start:'200',boot:'boot'}}],check,now)[0].state,'running');
assert.equal(A.endedProcesses([{...liveProcess,requestId:'pending'}],check,now)[0].state,'running');
console.log('Late liveness replies cannot overwrite a replaced process or pending request.');

assert.equal(A.recover([{...snapshot[0],targetStart:""}],now)[0].target,"");
assert.equal(A.recover(snapshot,now)[0].targetStart,"100");
const desktop={thread:'12345678-1234-1234-1234-123456789abc',handler:'codex.desktop'};
const desktopSession=A.normalize(JSON.stringify({...remembered,state:'done',targetCodex:desktop}),now);
assert.deepEqual(A.recover(A.snapshot([desktopSession]),now)[0].targetCodex,desktop);
assert.equal(A.normalize(JSON.stringify({...remembered,state:'done',targetCodex:{...desktop,thread:'new?prompt=bad'}}),now).targetCodex,null);
const zellij={session:'work',pane:3,socket:'/run/user/1000/zellij/protocol/work',binary:'/usr/bin/zellij',serverPid:123,serverStart:'100',boot:remembered.targetBoot,device:'1',inode:'2',binaryDevice:'1',binaryInode:'9'};
const paneSession=A.normalize(JSON.stringify({...remembered,state:'done',targetZellij:zellij}),now);
assert.deepEqual(A.recover(A.snapshot([paneSession]),now)[0].targetZellij,zellij);
assert.equal(A.normalize(JSON.stringify({...remembered,state:'done',targetZellij:{...zellij,pane:-1}}),now).targetZellij,null);
const server={id:'codex.server',kind:'agent',agent:'Codex',state:'idle',ttl:30};
let observed=A.serverSnapshot([], [server],now);
assert.equal(observed.items[0].state,'idle');assert.equal(observed.events.length,0);
observed=A.serverSnapshot(observed.items,[{...server,state:'running'}],now+1);
observed=A.serverSnapshot(observed.items,[server],now+2);
assert.equal(observed.items[0].state,'done');assert.equal(observed.events.length,1);
assert.equal(A.serverSnapshot(observed.items,[server],now+3).events.length,0);
assert.equal(A.serverSnapshot(observed.items,[],now+3).items.length,0);
assert.equal(A.serverSnapshot([agent],[],now).items[0],agent);
assert.equal(P.clean({}).codexServerStatus,false);
assert.equal(P.clean({codexServerPath:'ws://host'}).codexServerPath,'');
console.log('Codex server snapshots distinguish initial idle from observed completion and preserve non-observer activities.');
