const assert=require('node:assert/strict');
const {context}=require('../NotchPolicy.js');
assert.equal(context(null).id,'idle');
const media={state:'playing',title:'Track',live:{timers:[],timerActive:false,focused:null},workspace:{meetingSummary:''},notifications:{preview:''}};
assert.equal(context(media).id,'music');
media.live.timerActive=true;media.live.summary='10:00 · Focus';media.live.selectedTimer='a';
assert.equal(context(media).timerId,'a');
media.live.focused={state:'waiting',title:'Needs input'};
assert.equal(context(media).id,'activity');
media.live.attentionItems=[{},{},{}];
assert.equal(context(media).title,'3 need you');
media.live.timers=[{id:'b',status:'done',label:'Tea'}];
assert.equal(context(media).timerId,'b');
assert.equal(context(media).attention,true);
media.live={timers:[],timerActive:false,focused:null};media.state='paused';
assert.equal(context(media).id,'idle');
media.workspace.meetingSummary='Now · Meeting';assert.equal(context(media).id,'calendar');
media.workspace.meetingSummary='';media.notifications.preview='Notice';assert.equal(context(media).id,'inbox');
const prefs=require('../PreferencesPolicy.js');
assert.equal(prefs.clean({}).layoutMode,'notch');
assert.equal(prefs.clean({layoutMode:'strip'}).layoutMode,'strip');
assert.equal(prefs.clean({layoutMode:'pill'}).layoutMode,'notch');
console.log('Notch priority, exact timer routing, quiet paused state and presentation preference passed.');
